name: the_quran
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it:
  freezed_annotation:
  json_annotation:
  bloc:
  flutter_bloc:
  hydrated_bloc: 
  flutter_svg: 
  equatable: 
  dio: 
  device_preview: 
  path_provider: 
  bottom_bar_matu: 
  share_plus:
  audioplayers:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  hive_generator:
  json_serializable:
  flutter_lints:

flutter:

  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/svg/
    - assets/json/suar/
    - assets/json/juz_numbers/
    - assets/json/hizb_number/
    - assets/json/

  fonts:
    - family: amiri
      fonts:
        - asset: assets/fonts/amiri/amiri.ttf

    - family: quran
      fonts:
        - asset: assets/fonts/quran_font.ttf
    
    - family: frame
      fonts:
        - asset: assets/fonts/frame.ttf

    - family: surah_name
      fonts:
        - asset: assets/fonts/surah_name.ttf

    - family: basmala
      fonts:
        - asset: assets/fonts/basmala.ttf

    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/poppins.ttf
        - asset: assets/fonts/poppins/poppins-bold.ttf
          weight: 900  