name: the_quran
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it:
  freezed_annotation:
  json_annotation:
  bloc:
  flutter_bloc:
  hydrated_bloc: 
  flutter_svg: 
  equatable: 
  dio: 
  device_preview: 
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:

  json_serializable:

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/lang/en.json
    - assets/lang/ar.json
    - assets/images/svg/

  fonts:
    - family: amiri
      fonts:
        - asset: assets/fonts/amiri/amiri.ttf

    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/poppins.ttf